spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp
google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    user-agent: Mozilla/5.0
    public: 6LfTixkUAAAAAAnoLauOxDDtGY5kV37xoRpNy6ew
    private: 6LfTixkUAAAAAGIo_LcFUg46PsxCvOyZuSeDJ_Ns
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'