USE data;

SET foreign_key_checks = 0;

INSERT INTO `data`.`Contact` (`userID`, `Email`, `PESEL`, `phone`, `street`, `city`) VALUES ('1', 'mati@edu.p.lodz.pl', '89798355652', '767332112', 'kardynalna', 'Warszawa');
INSERT INTO `data`.`Contact` (`userID`, `Email`, `PESEL`, `phone`, `street`, `city`) VALUES ('2', 'ziomeczek12@edu.p.lodz.pl', '89010178909', '556677888', 'kozietulskiego', 'Łódź');
INSERT INTO `data`.`Contact` (`userID`, `Email`, `PESEL`, `phone`, `street`, `city`) VALUES ('3', '123763@edu.p.lodz.pl', '77090188923', '701889203', 'kaliska', 'Poznań');

INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('1', 'Laboratorium', '15', '14');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('2', 'Cwiczenia', '30', '28');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('3', 'Wyklad', '15', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('4', 'Laboratorium', '15', '14');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('8', 'Cwiczenia', '7', '6');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('8', 'Wyklad', '15', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('7', 'Laboratorium', '15', '14');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('7', 'Wyklad', '30', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('6', 'Laboratorium', '15', '14');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('6', 'Wyklad', '30', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('1', 'Wyklad', '30', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('2', 'Wyklad', '30', '0');
INSERT INTO `data`.`TeacherCourse` (`subjectID`, `type`, `coursesQuantity`, `minPresence`) VALUES ('3', 'Laboratorium', '30', '28');

INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:01:19');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:01:30');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:02:07');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:02:18');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:02:27');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:03:03');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:03:10');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:03:17');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:03:24');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:03:30');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:04:08');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:04:17');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:04:28');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:05:05');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:05:17');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('1', '08:15:00', '09:45:00', '2015:05:28');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:09:02');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:09:03');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:09:07');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:09:10');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:09:15');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:09:19');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:09:24');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:09:27');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:09:30');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:10:02');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:10:03');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:10:05');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:10:08');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:10:14');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:10:17');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:10:22');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:10:27');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:11:01');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:11:03');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:11:08');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:11:13');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:11:15');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:11:19');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:11:22');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:11:24');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:11:30');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:12:01');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:12:04');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:12:06');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:12:10');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '08:15:00', '09:45:00', '2015:12:17');
INSERT INTO `data`.`CourseDate` (`courseID`, `startTime`, `finishTime`, `date`) VALUES ('2', '12:15:00', '13:45:00', '2015:12:22');

INSERT INTO `data`.`Department` (`name`) VALUES ('Elektrotechniki, Elektroniki, Informatyki i Automatyki');
INSERT INTO `data`.`Department` (`name`) VALUES ('Fizyki Technicznej i Matematyki Stosowanej');
INSERT INTO `data`.`Department` (`Name`) VALUES ('Mechaniczny');
INSERT INTO `data`.`Department` (`Name`) VALUES ('Biotechnologii');
INSERT INTO `data`.`Department` (`Name`) VALUES ('Chemii');

INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Analiza matematyczna', '1', 'Zajecia z analizy matematycznej, obowiazkowej dla kazdego kierunku inxynierskiego');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Podstawy programowania', '1', 'Podstawy jezyka C');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Zaawansowane programowanie obiektowe', '1', 'Obiektowosc, watki, kolekcje w jezyku JAVA');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Bazy danych', '1', 'MySQL');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Fizyka 1', '2', 'Mechanika kwantowa');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Projektowanie aplikacji internetowych', '1', 'Podstawy tworzenia aplikacji internetowych w jezyku JAVA');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`) VALUES ('Statystyka', '1');
INSERT INTO `data`.`Subject` (`Name`, `departmentID`, `description`) VALUES ('Kryptografia', '3', 'Szyfr cezara, szyfr afiniczny, klucz publiczny i prywatny');

INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `index`, `type`, `password`, `Status`) VALUES ('mateuszek', 'Mateusz', 'Wieczorek', '187835', 'Student', 'maslo123', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `index`, `type`, `password`, `Status`) VALUES ('janek123','Jan', 'Nowak', '210231', 'Student', 'dupa123', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `index`, `type`, `password`, `Status`) VALUES ('tobi90', 'Tobiasz', 'Kowalski', '188291', 'Student', 'password1', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `index`, `type`, `password`, `Status`) VALUES ('G12', 'Grzegorz', 'Maslowski', '139111', 'Teacher', 'passwd', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `type`, `password`, `Status`) VALUES ('zofia12', 'Zofia', 'Kaleta', 'Teacher', 'zofia12', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `type`, `password`, `Status`) VALUES ('marek9', 'Marek', 'Zdun', 'Teacher', 'mzdun', 'ACTIVE');
INSERT INTO `data`.`User` (`login`, `firstName`, `lastName`, `type`, `password`, `Status`) VALUES ('Igor', 'Igor', 'Dudek', 'Teacher', 'dudekigor', 'ACTIVE');

INSERT INTO `data`.`StudentCourse` (`studentID`, `courseID`) VALUES ('4', '5');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('4', '2');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('4', '3');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('4', '1');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('4', '23');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('5', '7');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('5', '27');
INSERT INTO `data`.`StudentCourse` (`teacherID`, `courseID`) VALUES ('5', '24');

INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.from.adress', 'dmcs.p.lodz.pl@gmail.com');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.from.username', 'dmcs.p.lodz.pl');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.from.password', 'dmcs1234');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.port', '587');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.host', 'smtp.gmail.com');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.smtp.auth', 'true');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('email.smtp.starttls.enable', 'true');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('sms.account_sid', 'AC3d8d5a6178f996ab92bdc4d2d5931e44');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('sms.auth_token', 'd181f81cfc1f9fa21efb427aebe1b67d');
INSERT INTO `data`.`AppProperty` (`name`, `value`) VALUES ('sms.from.number', '+48732230590');

SET foreign_key_checks = 1;